# Projeto

### 1. a

In [110]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

X = [[1,1],[0,1],[1,0],[0,0]]
y = [1,0,0,0]

#tanh=  , 
#verbose= mostra todas as iteracoes do erro
#max_iter= numero maximo de itecaoes(200 padrao)
#adam- defaul = ‘adam’ refers to a stochastic gradient-based optimizer proposed by Kingma, Diederik, and Jimmy Ba (entre )
#activation='tanh' = ‘tanh’, the hyperbolic tan function, returns f(x) = tanh(x).
#hidden_layer_sizes= 
#learning_rate{‘constant’, ‘invscaling’, ‘adaptive’}, default=’constant’
# learning_rate_init = [0.05, 0.25, 0.5, 1, 2] 
#huffle :bool, default=True  - Whether to shuffle samples in each iteration. Only used when solver=’sgd’ or ‘adam’.
# momentumfloat, default=0.9 - Momentum for gradient descent update. Should be between 0 and 1. Only used when solver=’sgd’

for i in [0.05, 0.25, 0.5, 1, 2]:
    modelo = MLPClassifier(activation='tanh',
                           hidden_layer_sizes=(16, 8),
                           solver='sgd', 
                           max_iter=1500,
                           learning_rate_init = i,
                           tol=0.0000100,
                           momentum=0.5,
                           shuffle=True)#,verbose=True)


    #treinar o modelo
    modelo.fit(X,y)

    pred = modelo.predict(X)
    print(pred)
    print(accuracy_score(pred, y))

[1 0 0 0]
1.0
[1 0 0 0]
1.0
[1 0 0 0]
1.0
[1 0 0 0]
1.0
[1 1 1 1]
0.25


### 1. B

In [109]:
import numpy as np
import random
from sklearn.neural_network import MLPClassifier


Padrao_A = np.array([1, 1, 1, 1,
              1, 0, 0, 1,
              1, 0, 0, 1,
              1, 1, 1, 1])

Padrao_B = np.array([1, 0, 0, 1,
              0, 1, 1, 0,
              0, 1, 1, 0,
              1, 0, 0, 1])

def random_pattern(length):
    return [[random.randint(0, 1) for i in range(length)]]

X = np.concatenate(([Padrao_A]*128, [Padrao_B]*128))
y = np.array([], dtype=int)
RANDOM_DATA_LENGTH = 1024 - (128 * 2)

for i in range(RANDOM_DATA_LENGTH):
    X = np.append(X, random_pattern(16), axis = 0)

np.random.shuffle(X)

for i in range(1024):
    if np.array_equal(X[i], Padrao_A):
        y = np.append(y, [1, 0])
    elif np.array_equal(X[i], Padrao_B):
        y = np.append(y, [0, 1])
    else:
        y = np.append(y, [0, 0])


y = np.reshape(y, (1024, 2))

modelo = MLPClassifier(activation='tanh',
                           hidden_layer_sizes=(16, 2),
                           solver='sgd', 
                           max_iter=1500,
                           learning_rate_init = i,
                           tol=0.0000100,
                           momentum=0.5,
                           shuffle=True)

#treinar o modelo
modelo.fit(X,y)

print("Dados:\n",np.concatenate(([Padrao_A], [Padrao_B], random_pattern(16))))
print("Predict :\n", modelo.predict(np.concatenate(([Padrao_A], [Padrao_B], random_pattern(16)))).round())


Dados:
 [[1 1 1 1 1 0 0 1 1 0 0 1 1 1 1 1]
 [1 0 0 1 0 1 1 0 0 1 1 0 1 0 0 1]
 [0 0 1 0 1 0 1 1 1 0 1 0 0 0 1 0]]
Predict :
 [[0 1]
 [0 1]
 [0 1]]


### 2

In [114]:
import numpy as np
import random
from sklearn.neural_network import MLPClassifier


Padrao_Quadrado=np.array([0,0,0,0,0,0,0,
                          0,1,1,1,1,1,0,
                          0,1,0,0,0,1,0,
                          0,1,0,0,0,1,0,
                          0,1,0,0,0,1,0,
                          0,1,1,1,1,1,0,
                          0,0,0,0,0,0,0])

Padrao_circulo =np.array([0,0,1,1,1,0,0,
                          0,1,0,0,0,1,0,
                          1,0,0,0,0,0,1,
                          1,0,0,0,0,0,1,
                          1,0,0,0,0,0,1,
                          0,1,0,0,0,1,0,
                          0,0,1,1,1,0,0])

Padrao_triangulo =  np.array([0,0,0,0,0,0,0,
                              0,0,0,1,0,0,0,
                              0,0,1,0,1,0,0,
                              0,1,0,0,0,1,0,
                              1,1,1,1,1,1,1,
                              0,0,0,0,0,0,0,
                              0,0,0,0,0,0,0])

Padrao_X =  np.array([1,0,0,0,0,0,1,
                      0,1,0,0,0,1,0,
                      0,0,1,0,1,0,0,
                      0,0,0,1,0,0,0,
                      0,0,1,0,1,0,0,
                      0,1,0,0,0,1,0,
                      1,0,0,0,0,0,1])

Padrao_I =np.array([0,0,0,0,0,0,0,
                    0,1,1,1,1,1,0,
                    0,0,0,1,0,0,0,
                    0,0,0,1,0,0,0,
                    0,0,0,1,0,0,0,
                    0,1,1,1,1,1,0,
                    0,0,0,0,0,0,0])

Padrao_Z =np.array([1,1,1,1,1,1,1,
                    0,0,0,0,0,1,0,
                    0,0,0,0,1,0,0,
                    0,0,0,1,0,0,0,
                    0,0,1,0,0,0,0,
                    0,1,0,0,0,0,0,
                    1,1,1,1,1,1,1])

Padrao_C =np.array([1,1,1,1,1,0,0,
                    1,0,0,0,0,0,0,
                    1,0,0,0,0,0,0,
                    1,0,0,0,0,0,0,
                    1,0,0,0,0,0,0,
                    1,0,0,0,0,0,0,
                    1,1,1,1,1,0,0,])


def random_pattern(length):
    return [[random.randint(0, 1) for i in range(length)]]

temp = ([Padrao_Quadrado]*128,[Padrao_C]*128,[Padrao_Z]*128,[Padrao_I]*128,[Padrao_X]*128,[Padrao_triangulo]*128,[Padrao_circulo]*128)
X = np.concatenate(temp)

random_data = 1024 - (128 * 7)

np.random.shuffle(X)

y = np.array([])
for i in range(1024):
    if np.array_equal(X[i], Padrao_Quadrado):
        y = np.append(y, [1,0,0,0,0,0,0])
    elif np.array_equal(X[i], Padrao_triangulo):
        y = np.append(y, [0,1,0,0,0,0,0])
    elif np.array_equal(X[i], Padrao_circulo):
        y = np.append(y, [0,0,1,0,0,0,0])
    elif np.array_equal(X[i], Padrao_C):
        y = np.append(y, [0,0,0,1,0,0,0])
    elif np.array_equal(X[i], Padrao_I):
        y = np.append(y, [0,0,0,0,1,0,0])
    elif np.array_equal(X[i], Padrao_X):
        y = np.append(y, [0,0,0,0,0,1,0])
    elif np.array_equal(X[i], Padrao_Z):
        y = np.append(y, [0,0,0,0,0,0,1])
    else:
        y = np.append(y, [0,0,0,0,0,0,0])
y = np.reshape(y, (1024,7))

modelo = MLPClassifier(activation='tanh',      
                       hidden_layer_sizes=(16, 8),
                           solver='sgd', 
                           max_iter=1500,
                           learning_rate_init = i,
                           tol=0.0000100,
                           momentum=0.5,
                           shuffle=True)

#treinar o modelo
modelo.fit(X,y)

r =  [Padrao_Quadrado], [Padrao_C], [Padrao_Z],[Padrao_I], [Padrao_X], [Padrao_triangulo], [Padrao_circulo]
print("Dados:\n",np.concatenate((r)))
print("Predict :\n", modelo.predict(np.concatenate((r))).round())


IndexError: index 896 is out of bounds for axis 0 with size 896